### ISSUE TITLE
Create Documentation for Sprint Tickets

### ISSUE THREAD

**Issue by vbono** [sweg3302-tune-town/tune-town#7]
What: Create a format for all sprint tickets to follow in Tune Town repo wiki

https://github.com/vbono/tune-town/wiki

Add any relevant information including breakdown of all labels/priority measures/ etc

DOC: format is agreed upon by all devs & documentation is uploaded

**Comment by johnambery** [comment]
I GPTed a quick template, im not sure if it's too much... are acceptance criteria and definition of done the same thing?
